crew_name: "Copy Crew"
usecase: "copy"
module_name: "copy"

crews:
  copy_crew:
#    knowledge_sources:
#      - "./docs/shared_project_guidelines.md"
#      - "./docs/style_guide.txt"
#    input:
#      source: "file"
#      path: "E:/Python/data/raw/features.json"
    steps:
      - task_key: "functionality_task"
        agent_key: "writer_config"
      - task_key: "usecase_task"
        agent_key: "usecase_config"
      - task_key: "verify_task"
        agent_key: "verifier_config"
      - task_key: "introduction_task"
        agent_key: "writer_config"
#    knowledge_sources:
#      - "./data/market_research_summary.csv"
#      - "./data/competitor_analysis.pdf"
#      - "./data/user_feedback.txt"


pipeline:
  - "document_crew"

